#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "Oy479/orrxmr"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 7

#define RGB_MATRIX_STARTUP_SPD 60

#define TAPPING_TERM 200
#define PERMISSIVE_HOLD
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
